# Generated by Django 4.0.3 on 2022-04-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Event Date'),
        ),
    ]
