# Generated by Django 4.0.3 on 2022-04-12 05:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_description_alter_event_event_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Event Time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_data',
            field=models.DateField(auto_now_add=True, verbose_name='Event Date'),
        ),
    ]
