# Generated by Django 4.0.3 on 2022-04-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_rename_apps_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='AppDevelopers',
        ),
        migrations.AddField(
            model_name='app',
            name='AppDevelopers',
            field=models.ManyToManyField(blank=True, to='events.myclubuser'),
        ),
    ]
