# Generated by Django 4.0.3 on 2022-04-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='imgsrc',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Image Source'),
        ),
    ]
