# Generated by Django 4.0.3 on 2022-04-12 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_event_time_alter_event_event_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_time',
        ),
    ]
