# Generated by Django 4.0.3 on 2022-04-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_event_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_data',
            field=models.DateTimeField(verbose_name='Event Date'),
        ),
    ]
