# Generated by Django 4.0.3 on 2022-04-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_event_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Event Date'),
        ),
    ]
