# Generated by Django 4.0.3 on 2022-04-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_remove_app_appdevelopers_app_appdevelopers'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='AppImage',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
