# Generated by Django 4.0.3 on 2022-04-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_app_appimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='AppBgColor',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Card Background'),
        ),
    ]
